"""Numbered source list for research_out.json. Every URL here was fetched in this
artifact or by its subagents (raw/ holds the grep/fetch output). Passages are
short exact strings from the page at that URL."""

WS_ROOT = "/ai-inventor/aii_data/runs/run_fcYd_7ruOwtm/3_invention_loop"

SOURCES = [
    # --- novelty: closest prior work ---
    dict(index=1, url="https://arxiv.org/abs/2406.11717", title="Refusal in Language Models Is Mediated by a Single Direction",
         authors=["Andy Arditi", "Oscar Obeso", "Aaquib Syed", "Daniel Paleka", "Nina Panickssery", "Wes Gurnee", "Neel Nanda"], year=2024,
         summary="Directional ablation and activation addition of a difference-in-means refusal direction across 13 open chat models. Mechanism evidence, not a model ranking. Closest prior work for C2 and C6.", supporting_passages=[]),
    dict(index=2, url="https://arxiv.org/pdf/2507.11878", title="LLMs Encode Harmfulness and Refusal Separately",
         authors=["Jiachen Zhao", "Jing Huang", "Zhengxuan Wu", "David Bau", "Weiyan Shi"], year=2025,
         summary="Separate harmfulness and refusal directions; harmfulness-direction steering on 3 chat models; harmfulness and refusal depth curves on the same models. Closest prior work for C1 and C10 (ADJACENT).",
         supporting_passages=[dict(quote="the refusal rate elicited by the harmfulness direction is much lower than that elicited directly by the refusal direction", locator="v5, Section 3.2, paragraph beside Figure 4")]),
    dict(index=3, url="https://failurefirst.org/research/reports/74-abliteration-jailbreak-orthogonality/", title="Failure-First Report 74 (abliteration-jailbreak orthogonality)",
         authors=None, year=2026,
         summary="Grey-literature web report (2026-03-11). It ranks 16 models by resistance to weight abliteration and correlates that with jailbreak refusal. It is the closest thing to the kill-check design (a generic directional-ablation outcome across models), and it found a null result.",
         supporting_passages=[dict(quote="the Spearman rank correlation between abliteration resistance and jailbreak refusal rate is rho = -0.003", locator="Executive Summary, paragraph 2")]),
    dict(index=4, url="https://arxiv.org/abs/2606.08044", title="When Behavioral Safety Evaluation Fails: A Representation-Level Perspective",
         authors=None, year=2026,
         summary="LVS: a per-model safety score from latent-perturbation sensitivity. The perturbation is undirected and the score is not correlated with any benchmark. Nearest causal cross-model score (kill-check runner-up).", supporting_passages=[]),
    dict(index=5, url="https://arxiv.org/abs/2603.14278", title="Activation Surgery: Jailbreaking White-box LLMs without Touching the Prompt",
         authors=None, year=2026,
         summary="Layer-wise substitution of a benign twin's activations, used as a jailbreak on mainly one model; no per-model score. C3 ADJACENT.", supporting_passages=[]),
    dict(index=6, url="https://github.com/JolanMc/Jorak", title="Model Scanner (Jorak): reference-free abliteration detection",
         authors=["JolanMc"], year=2026,
         summary="Weights-only, reference-free scanner that reads the SVD of o_proj/down_proj against the refusal axis and outputs a provenance label. Closest relative of C4 (ADJACENT: it labels models, it does not grade them).", supporting_passages=[]),
    dict(index=7, url="https://raw.githubusercontent.com/JolanMc/Jorak/8147de343964a3cced37db71814e9007c7465a52/modelscanner/classifier/scanner.py",
         title="Jorak modelscanner/classifier/scanner.py @ 8147de3", authors=["JolanMc"], year=2026,
         summary="Pinned threshold file. All three weight-signal thresholds are 0.5, calibrated on Qwen2.5-0.5B. No 0.35 threshold exists anywhere in the repository.",
         supporting_passages=[dict(quote="svd_align_severed: float = 0.5", locator="line 48"),
                              dict(quote="subspace_severed: float = 0.5", locator="line 55"),
                              dict(quote="alignement SVD u_min : 0.24 vs 1.00   -> seuil sectionné 0.5", locator="Thresholds docstring, line 44")]),
    dict(index=8, url="https://arxiv.org/abs/2604.27401", title="Perturbation Probing: A Two-Pass-per-Prompt Diagnostic for FFN Behavioral Circuits",
         authors=None, year=2026,
         summary="An FFN/Skip ratio predicts neuron-ablation effectiveness across 13 models and 4 families (R^2 = 0.81). The ratio mixes weights and activations, and the target is an ablation outcome, not a benchmark. Nearest miss for C5 (NEW).", supporting_passages=[]),
    dict(index=9, url="https://arxiv.org/abs/2410.13708", title="On the Role of Attention Heads in Large Language Model Safety",
         authors=None, year=2024, summary="Ships/Sahara safety-head attribution on two same-lineage models. C6/C7 ADJACENT.", supporting_passages=[]),
    dict(index=10, url="https://arxiv.org/abs/2410.16327", title="Feint and Attack: Attention-Based Strategies for Jailbreaking and Protecting LLMs",
         authors=None, year=2024, summary="Attention to sensitive words correlates with jailbreak success, within the Llama-2 family and across attack methods. C7 ADJACENT.", supporting_passages=[]),
    dict(index=11, url="https://arxiv.org/abs/2402.13494", title="GradSafe: Detecting Jailbreak Prompts for LLMs via Safety-Critical Gradient Analysis",
         authors=None, year=2024, summary="Parameter-gradient (not input-gradient) safety attribution in one family. C8 ADJACENT.", supporting_passages=[]),
    dict(index=12, url="https://arxiv.org/html/2502.13946v2", title="Why Safeguarded Ships Run Aground? Aligned Large Language Models' Safety Mechanisms Tend to Be Anchored in The Template Region",
         authors=["Chak Tou Leong"], year=2025,
         summary="Template-region normalized indirect effect of the refusal/compliance decision, compared across 6 chat models from 4 families and tied to vulnerability (TempPatch). C9 PUBLISHED.",
         supporting_passages=[dict(quote="For a fair cross-model comparison, we use the normalized indirect effect (NIE)", locator="Section 3.3, Method/Results")]),
    dict(index=13, url="https://arxiv.org/abs/2609.13534", title="Harmfulness Propagation Dynamics: Layer-wise Trajectories of Adversarial Intent",
         authors=None, year=2026, summary="Harm-only depth trajectories used as per-prompt detection features across 4 families. C10 ADJACENT.", supporting_passages=[]),
    dict(index=14, url="https://arxiv.org/abs/2406.05946", title="Safety Alignment Should Be Made More Than Just a Few Tokens Deep",
         authors=["Xiangyu Qi"], year=2024, summary="Per-token KL between aligned and base models over the first tokens. This needs the parent model. C11 ADJACENT.", supporting_passages=[]),
    dict(index=15, url="https://arxiv.org/abs/2609.18471", title="First Token Matters: Understanding Safety Collapse in Large Reasoning Models",
         authors=None, year=2026, summary="Refusal-projection trajectory that needs a counterpart model (3 instruct/reasoning pairs). C11 ADJACENT.", supporting_passages=[]),
    dict(index=16, url="https://arxiv.org/abs/2603.27412", title="The Geometry of Harmful Intent: Training-Free Anomaly Detection via Angular Deviation in LLM Residual Streams (LatentBiopsy)",
         authors=["Isaac Llorente-Saguer"], year=2026,
         summary="Harmful-vs-XSTest-benign-aggressive AUROC per checkpoint (6 checkpoints, 2 families) as evidence of geometric invariance; no plain-benign baseline ratio. C12 ADJACENT.",
         supporting_passages=[dict(quote="AUROC = 1.000 for discriminating harmful from benign-aggressive prompts (XSTest)", locator="Abstract, v1")]),
    dict(index=17, url="https://arxiv.org/abs/2607.13075", title="The Entanglement Wall: Activation-Space Probes as Risk Detectors, Not Context Adjudicators",
         authors=["Dominik Schwarz"], year=2026, summary="Twin/paired probe separation across families; explicitly declines ranking use. C12/C13 ADJACENT.", supporting_passages=[]),
    dict(index=18, url="https://arxiv.org/abs/2608.09624", title="Measuring the Wrong Thing: Internal Harmfulness Scores Anti-Rank Successful Jailbreaks",
         authors=["Mingyu Luo"], year=2026, summary="Wrapped-vs-plain harmful-intent AUROC per model (0.936 -> 0.803), framed as a critique of measurement validity. C13 ADJACENT.", supporting_passages=[]),
    dict(index=19, url="https://arxiv.org/abs/2606.22676", title="Skin-Deep: A Geometric Diagnostic for Alignment Fragility in Large Language Model Representations",
         authors=None, year=2026, summary="GFS with a fixed l/L depth weight (not fitted) across 21 models; parent-dependent (iteration-1 finding). Nearest miss for C14 (NEW).", supporting_passages=[]),
    dict(index=20, url="https://arxiv.org/abs/2606.25750", title="RAS: Measuring LLM Safety Through Refusal Alignment",
         authors=["Chang-Chieh Huang"], year=2026, summary="Calibrated 0-100 white-box safety score with a fixed average and a hand-set logistic; needs a per-family reference model. Nearest miss for C14.", supporting_passages=[]),
    dict(index=21, url="https://arxiv.org/abs/2605.30018", title="Latent Performance Profiling of Large Language Models",
         authors=None, year=2026, summary="Effective rank and participation ratio across 8 LLMs, used as capability profiles, not safety. Nearest miss for C15 (NEW).", supporting_passages=[]),
    dict(index=22, url="https://arxiv.org/abs/2401.17139", title="Diff-eRank: A Novel Rank-Based Metric for Evaluating Large Language Models",
         authors=None, year=2024, summary="Effective-rank model metric for capability. C15 nearest miss.", supporting_passages=[]),
    dict(index=23, url="https://arxiv.org/abs/2608.25390", title="Refusal geometry reflects refusal training: diverse refusal prefixes can raise stable rank and weaken refusal vector ablation attacks",
         authors=["Andrey Labunets"], year=2026,
         summary="Found in the orchestrator's adversarial pass. Links the stable rank of refusal residuals and gradients to robustness against ablation, in one OLMo-2-1B lineage. New nearest miss for C15; C15 stays NEW.",
         supporting_passages=[dict(quote="diverse refusal starts can raise stable ranks of gradients and activation changes, making refusals harder to remove with a vector ablation attack", locator="Abstract, v2")]),
    dict(index=24, url="https://arxiv.org/html/2603.24543", title="Analysing the Safety Pitfalls of Steering Vectors",
         authors=["Yuxiao Li"], year=2026,
         summary="Per-model OLS slope gamma_1 of the ASR dose-response slope on steering-vector/refusal-direction cosine, compared across 6 models by scale. C16 PUBLISHED (comparator).",
         supporting_passages=[dict(quote="becomes progressively steeper with model size", locator="Section 6, 'Effect of model scale'; Table 1 (gamma_1 from -36.52 for Llama 7B to -193.40 for Qwen 32B)")]),
    dict(index=25, url="https://arxiv.org/abs/2407.12404", title="Analyzing the Generalization and Reliability of Steering Vectors",
         authors=["Daniel Tan", "David Chanin", "Aengus Lynch", "Dimitrios Kanoulas", "Brooks Paige", "Adria Garriga-Alonso", "Robert Kirk"], year=2024,
         summary="The real 'Tan et al.' steering-reliability paper. The draft had attributed this to 2406.09289.", supporting_passages=[]),
    dict(index=26, url="https://arxiv.org/abs/2406.09289", title="Understanding Jailbreak Success: A Study of Latent Space Dynamics in Large Language Models",
         authors=["Sarah Ball", "Frauke Kreuter", "Nina Rimsky"], year=2024,
         summary="Ball, Kreuter & Rimsky (not Tan et al.). Jailbreak latent dynamics.", supporting_passages=[]),
    # --- incumbents / kill-check non-causal ---
    dict(index=27, url="https://arxiv.org/abs/2608.05578", title="Detecting Safety Training Modification in Language Models via Activation Analysis (AMS)",
         authors=["Glen Messenger"], year=2026,
         summary="AMS sigma is a non-causal standardized projection separation. The arXiv page lists the IEEE Access DOI 10.1109/ACCESS.2026.3704057.", supporting_passages=[]),
    dict(index=28, url="https://arxiv.org/abs/2511.14195", title="N-GLARE: An Non-Generative Latent Representation-Efficient LLM Safety Evaluator",
         authors=["Zheyu Lin"], year=2026, summary="JSS-trajectory stability ratio under 4 probing conditions; closest to C13 in functional form (incumbent map).", supporting_passages=[]),
    # --- bibliography verification ---
    dict(index=29, url="https://api.crossref.org/works/10.1145/3630106.3659037", title="Crossref record: Black-Box Access is Insufficient for Rigorous AI Audits",
         authors=None, year=2024, summary="Confirms the Casper DOI (FAccT '24, pp. 2254-2272). The planner's 'bogus eprint 0106.36590' is a fragment of this correct DOI.", supporting_passages=[]),
    dict(index=30, url="https://api.crossref.org/works/10.1109/ACCESS.2026.3704057", title="Crossref record: Detecting Safety Training Modification in Language Models via Activation Analysis",
         authors=None, year=2026, summary="Confirms the full AMS DOI, IEEE Access vol. 14, pp. 91723-91737. The 'truncated fragment 2026.37040' is a substring of it.", supporting_passages=[]),
    dict(index=31, url="https://arxiv.org/abs/2508.20766", title="Turning the Spell Around: Lightweight Alignment Amplification via Rank-One Safety Injection",
         authors=["Harethah Abu Shairah", "Hasan Abed Al Kader Hammoud", "George Turkiyyah", "Bernard Ghanem"], year=2025,
         summary="ROSI; full first-author name verified.", supporting_passages=[]),
    dict(index=32, url="https://arxiv.org/abs/2608.05086", title="Item Response Theory for AI Safety",
         authors=["Joshua Fonseca Rivera", "Neil Shah", "David Demitri Africa", "Konstantinos Voudouris"], year=2026,
         summary="Rivera2026 authors verified. The affiliation 'Independent / UK AI Security Institute' had been merged into the author field.", supporting_passages=[]),
    dict(index=33, url="https://arxiv.org/abs/2606.16349", title="From Refusal Geometry to Safety Geometry: Harmfulness--Refusal Coupling under Dynamic Adversarial Fine-Tuning",
         authors=["Wenhao Lan", "Shan Li", "Xinhua Lai", "Meiqi Wu", "Junbin Yang", "Haihua Shen"], year=2026, summary="Lan2026 ID and authors verified (HRCI).", supporting_passages=[]),
    dict(index=34, url="https://arxiv.org/abs/2602.04653", title="Inference-Time Backdoors via Chat Templates: From LLM Supply Chains to Agentic System Compromise",
         authors=["Ariel Fogel", "Omer Hofman", "Eilon Cohen", "Roman Vainshtein"], year=2026, summary="Fogel2026 ID verified.", supporting_passages=[]),
    dict(index=35, url="https://arxiv.org/pdf/2510.14276", title="Qwen3Guard Technical Report",
         authors=None, year=2025, summary="Section 3.5 describes Safety RL on Qwen3-4B with Qwen3Guard-4B-Gen as the reward. This confirms Qwen3Guard must not judge SafeRL.",
         supporting_passages=[dict(quote="Application I: Safety RL with Generative Qwen3Guard", locator="Section 3.5 heading")]),
    dict(index=36, url="https://export.arxiv.org/api/query", title="arXiv API (id_list batch metadata)",
         authors=None, year=None, summary="Source of every author list, title and version in references.bib (raw/arxiv_atom_*.xml).", supporting_passages=[]),
    dict(index=37, url="https://api.github.com/repos/JolanMc/Jorak/commits?path=modelscanner/classifier/scanner.py&per_page=100", title="GitHub API: Jorak scanner.py commit history",
         authors=None, year=2026, summary="Three commits touched scanner.py (27957d6 on 2026-07-15, 239fbdb on 2026-07-15, 0351eda on 2026-07-20). The thresholds are 0.5 in all of them.", supporting_passages=[]),
    dict(index=41, url="https://arxiv.org/abs/2502.16173", title="Mapping 1,000+ Language Models via the Log-Likelihood Vector",
         authors=["Momose Oyama"], year=2025, summary="Model-map precedent for a metamodel over model representations (output log-likelihoods, not activations). C14 nearest miss.", supporting_passages=[]),
    dict(index=42, url="https://arxiv.org/abs/2410.03415", title="Surgical, Cheap, and Flexible: Mitigating False Refusal in Language Models via Single Vector Ablation",
         authors=None, year=2024, summary="False-refusal vector ablation. Single-model tool; C2/C12 adjacent.", supporting_passages=[]),
]
